DROP TABLE MATRICULA;
DROP TABLE ALUMNO;
DROP TABLE CURSO;

CREATE TABLE ALUMNO(
    CODIGO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100),
    PROMEDIO NUMERIC(4, 2),
    CREDITO_DISPONIBLE NUMERIC(7,2),
    FECHA_NACIMIENTO DATE
);

CREATE TABLE CURSO(
    CODIGO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100),
    CREDITOS NUMERIC(1),
    COSTO NUMERIC(5,2)
);

CREATE TABLE MATRICULA(
    COD_ALU INTEGER REFERENCES ALUMNO,
    COD_CURSO INTEGER REFERENCES CURSO,
    PRIMARY KEY(COD_ALU, COD_CURSO),
    NOTA NUMERIC(4,2)
);

